version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: usuario
      POSTGRES_USER: java
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
